### PR TITLE
Delay W0010 (not available) warning message

### PR DESCRIPTION
**Pull request by ollo69**
Because I hate to have a warning message every time that my SkyQ reboot to update firmware, I just would like to add a delay of 3 minutes before logging the warning. After 3 minutes if device is still unavailable the warning will be issued, if device become online before, device is back available without any warning in the log.

### CODE REVIEW

**Comment by RogerSelwyn** [comment]
Thanks for the input. I'm not sure I'm happy that a three minute delay be added whenever the box goes unavailable. If you could localise it to just when a firmware update is happening, then it would be ok, but I'm not sure how that would be identifiable.

I've no idea how often SkyQ updates happen, but I'm guessing no more than once a month (I'm sure you will prove me wrong), is it really so much of a problem?

As I side point, a simpler way of implementing this would be to change the ERROR_TIMEOUT constant which currently restricts the warning to occur after a minimum of 10 seconds. This is to remove nuisance warnings, but still display a debug message every time an update cycle occurs ahead of the timeout. 

If you want to make that change in your environment, it can be modified in const.py, but will of course get overwritten should you update the integration via HACS.

**Comment by ollo69** [comment]
As I understand `ERROR_TIMEOUT` is intended as a delay before set the device status `unavailable`, for this reason I do not change that constant (and the behavior). The meaning of this change is just to delay the warning message, the unavailable status will be maintained with same timing, because this is the real status of the device. 

Unfortunately there are no way to identify a firmware update, because this is just a reboot to have the new firmware version working . But delay the warning message will be probably helpful also in case of a controlled restart of the device or a temporary power failure.

Generally speaking, as I know, the HA core team recommend to avoid as much as possible log message, and because warning message are shown in the log registry page could confuse basic users (that at end will simply ignore them, while should not).

I don't know the frequency of firmware update from Sky, but occur very often that the device reboot in the night when is in stand-by. May be is just a scheduled reboot to refresh memory, but it occur nearly to every night.

**Comment by ollo69** [comment]
Ok, that's fine, I'll try to further investigate the behavior of my box. 
At this moment I manually apply this change in my env, so I will see next nights what will happen, crossing log message and the device status in the registry. Issue is not related to ECO mode, I just disabled it at all. My log level is set to INFO as default, but in HA Log registry page are shown only messages from WARN level (until you don't load all the registry), and I would have this page clean, until I have a real problem.

I'm still convinced that is useless give a warning message if the box come unavailable for a limited time (as for a reboot), because there are nothing to warn about and is still possible to see status change just using HA registry.

**Comment by RogerSelwyn** [comment]
I'm not sure I know what you mean by the HA Log registry page, do you mean the system log?

If you can check if the reboot happens at the same time every night, it may be possible to build something around that.

**Comment by ollo69** [comment]
> I'm not sure I know what you mean by the HA Log registry page, do you mean the system log?

Settings -> System -> Registry. There are shown the log message occurred with levels >= WARN. This page is useful to see if there are some issue without directly opening the log file.


> If you can check if the reboot happens at the same time every night, it may be possible to build something around that.

Not the same time, because nothing happen until the device is not in standby. And when I spent many hours with a new TV series, it can stay on until very late night😉. And in any case seems too complex that just delay a log some minutes😊

**Comment by RogerSelwyn** [comment]
I have no such page on my systems

CF9ABFB6-D31E-4876-8364-35EADA75A9BC

**Comment by ollo69** [comment]
Sorry, is `Logs`. I was just translating from Italian, and Log was translated Registry😊. 
As you see in description they say "View and search log to diagnose issues", and they shown message with levels >= WARN. So because a reboot in my opinion is not an issue I would not have that message there. That's my point.

**Comment by RogerSelwyn** [comment]
I understand your point, but it isn't possible to identify a simple reboot from any other problem. If any of my devices go offline, I'd expect a warning message almost immediately rather than several minutes later. I'm investigating reboot issues to see if it is standard overnight.

**Comment by RogerSelwyn** [comment]
From what I can see all boxes reboot overnight (which I never knew) https://helpforum.sky.com/t5/Sky-Q/Sky-Q-Box-takes-off-at-about-5am-each-morning/td-p/3904627. Seem unnecessary to me, just handling rubbish code errors.

I'll think on it.

**Comment by ollo69** [comment]
> I understand your point, but it isn't possible to identify a simple reboot from any other problem. If any of my devices go offline, I'd expect a warning message almost immediately rather than several minutes later. I'm investigating reboot issues to see if it is standard overnight.

But due to this you don't know if you really have an issue if you don't wait some minutes, to just see if the device was just rebooting. And if you really want to be notified immediately when your device go offline, you can create an automation than will send an e-mail when the device status is not available.

**Comment by RogerSelwyn** [comment]
As I said, I'll think on it.

**Comment by ollo69** [comment]
Just to give you some additional background:
- My SkyQ Platinum restart basically every night. Restart occur when the device is in StandBy and no SkyQ Mini associated are streaming from the main SkyQ
- I found an italian forum where many user was complaining about this. The answer was that because SkyQ device hang if it run multiple days, they just apply this work-aroud to avoid to much call to the service desk.

Eventually what about add this delay as configuration option?

**Comment by ollo69** [comment]
No problem and no urgency. Was just to inform you on my research.

**Comment by RogerSelwyn** [comment]
Please can you try v2.9.9 Beta 1. It is a significantly different set of code to your changes, so I didn't build on your PR. 

It basically checks if it is during the overnight 'quiet time' of 02:30 to 06:00 (this gives some leeway around actual sleep hours). If the box is in ECO mode (it relies on why the box last 'woke' to identify, I can't find the actual setting in the api), then it will put an I0030 message, and a W0010 it is still down after 6am. 

For your case it checks for the same quiet time, though I hear that the reboot typically happens around 5am. If the box goes down it puts out a I0040, and then a W0010 if still down after 3 minutes. I suspect it will do a W0010 again at 6am if still down (sorry it's just messing with my head how to handle all the conditions without too much horrible code).

https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.9.9b1

**Comment by ollo69** [comment]
> Please can you try v2.9.9 Beta 1. It is a significantly different set of code to your changes, so I didn't build on your PR.

Thanks, I'll try, but I'm quite sure that quiet time 02:30 to 06:00 is not good for me in normal condition (I mean when I go to sleep at around midnight😊). I was monitoring my devices in last 2 days, and both SkyQ Platinum and SkyQ Mini reboot about at 1.00 PM (with 15 minutes of difference).

image

SkyQ Mini below goes to unavailable 2 times because the second time is due to reboot of main SkyQ Platinum

image

May be could be an option let enable and configure this time windows as configuration option?

**Comment by RogerSelwyn** [comment]
I’ll change the quiet time slot for reboot scenario. Fairly easy to do, I need to rework the code it is too complex at the moment. I may well and an option as well, but I don’t really like having loads and loads of options.

**Comment by RogerSelwyn** [comment]
Just do a tweak in const.py for the relevant time period for now, and I can fix it in the next version.

**Comment by ollo69** [comment]
Ok, installed new version and set start of quiet time to `0045` in `const.py`.
Let this run a couple of days, I'll report you here results of my tests,

**Comment by ollo69** [comment]
Sorry but probably I bad understand your changes. You still leave the delay of 3 minutes in case of reboot? If yes my tweak in `const.py` is not necessary.

**Comment by RogerSelwyn** [comment]
Yes it has 3 mins, but only between 2:30 and 06:00

**Comment by ollo69** [comment]
Ok. So now I set from 0:45 to 06:00.👍

**Comment by RogerSelwyn** [comment]
I’d be interested at what time you get I0040

**Comment by ollo69** [comment]
Seems not working. My SkyQ devices reboot at same time:

SkyQ Platinum:
image

SkyQ Mini:
image

and in the log I have warning for all reboot:

image

SkyQ Mini takes longer than 3 minutes to become online after SkyQ Platinum reboot, this sometimes occur. Other 2 events take less that 3 minutes but the warning is in the log.

**Comment by RogerSelwyn** [comment]
Did you get an i0040 as well. If it takes longer than 3 minutes you will get a w0010 as well? Did you restart ha after changing the time in const.py?

**Comment by RogerSelwyn** [comment]
I think I may know what is going on. Let me think...

**Comment by RogerSelwyn** [comment]
Can you get me the out put of:

`http://192.168.1.122:9006/as/system/time`

and

`http://192.168.1.122:9006/as/system/information`

**Comment by ollo69** [comment]
This is platinum, let me know if you also need information from mini

Information:

```
{
   "ASVersion" : "Q200.000.28.00-AS_26.2.0",
   "CAType" : "VIDEOGUARD",
   "DRMActivationStatus" : true,
   "IPAddress" : "192.168.10.15",
   "MACAddress" : *REDACTED*,
   "activeStandby" : true,
   "airplayID" : "Sky Q 2TB Box8963",
   "btID" : "Sky Q 2TB Box8963",
   "cable" : false,
   "chipID" : "265 684 0898 8",
   "deviceID" : *REDACTED*,
   "deviceType" : "GATEWAYSTB",
   "gateway" : true,
   "gatewayIPAddress" : "not MR",
   "hardwareModel" : "ES240",
   "hardwareName" : "Falcon",
   "hdrCapable" : true,
   "householdToken" : *REDACTED*,
   "localIRDatabase" : true,
   "manufacturer" : "Sky",
   "meshEnabled" : true,
   "modelNumber" : "Q200.000.28.00L (5ighpf4)",
   "networkVersion" : "2.00",
   "numDTTTuners" : 4,
   "pipCapable" : true,
   "purchasebalance" : "0.01",
   "purchaselimit" : "30.01",
   "receiverID" : *REDACTED*,
   "serialNumber" : *REDACTED*,
   "subscriberID" : "*REDACTED*,
   "systemUptime" : 31962,
   "uhdCapable" : true,
   "versionNumber" : "32B189",
   "viewingCardNumber" : *REDACTED*,
   "wakeReason" : "RESET"
}
```

Time:

```
{
   "futureLocalTimeOffset" : 3600,
   "futureTransitionUtc" : 1667091600,
   "presentLocalTimeOffset" : 7200,
   "utc" : 1660551340,
   "version" : 7
}
```

Just for your information, there are no `i0040` in the log, and of course I reboot HA after changing `const.py`.

**Comment by RogerSelwyn** [comment]
I’m testing a major rewrite of that code, should release a version in the next couple of days. As matter of interest I set my main box to ‘Active’ and it rebooted at 4am

**Comment by RogerSelwyn** [comment]
Please try this version - https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.9.9

**Comment by ollo69** [comment]
Installed. Do have to tweak `const.py` to change "quiet time" interval?

**Comment by RogerSelwyn** [comment]
Shouldn't have to. Set from 00:45 to 06:00

**Comment by ollo69** [comment]
Here result after first night:

```
2022-08-21 03:05:01.304 INFO (MainThread) [custom_components.skyq.classes.power] I0040 - Device is not available. Nightly reboot?: SkyQ Mini Letto
2022-08-21 03:06:56.090 INFO (MainThread) [custom_components.skyq.classes.power] I0010 - Device is now available: SkyQ Mini Letto

 ....

2022-08-21 04:30:21.972 INFO (MainThread) [custom_components.skyq.classes.power] I0040 - Device is not available. Nightly reboot?: SkyQ Platinum
2022-08-21 04:30:51.885 INFO (MainThread) [custom_components.skyq.classes.power] I0040 - Device is not available. Nightly reboot?: SkyQ Mini Letto
2022-08-21 04:32:26.171 INFO (MainThread) [custom_components.skyq.classes.power] I0010 - Device is now available: SkyQ Platinum
2022-08-21 04:32:33.177 INFO (MainThread) [custom_components.skyq.sensor] I0020 - Device is not available overnight, ECO/reboot?: SkyQ Platinum Used Storage
2022-08-21 04:33:39.041 WARNING (MainThread) [custom_components.skyq.classes.power] W0020 - Device is not available: SkyQ Mini Letto
2022-08-21 04:35:36.006 INFO (MainThread) [custom_components.skyq.classes.power] I0010 - Device is now available: SkyQ Mini Letto
2022-08-21 04:37:33.180 INFO (MainThread) [custom_components.skyq.sensor] I0010 - Device is now available: SkyQ Platinum Used Storage

```

There is just 1 `W0020` related to the SkyQ Mini after reboot of SkyQ Platinum, because the mini takes longer to reconect to the platinum after reboot (about 5 minutes as you can see in the log). I think that this is quite random, I see some times that it reconnect faster.

So, seems good, you could extend the wait time to 5-6 minutes to avoid warning for `mini` on main device reboot or just leave it as is.

**Comment by RogerSelwyn** [comment]
I’ll see if I can set it to 6 mins for a mini

**Comment by RogerSelwyn** [comment]
By the way you can adjust the timeout, it is in constant.py

**Comment by ollo69** [comment]
Yes, but it will be overwritten every update, I prefer avoid this...

**Comment by RogerSelwyn** [comment]
I only meant temporarily.  I'll get it done in the next couple of a days.

**Comment by ollo69** [comment]
A, ok. Don't worry, I will leave as is and monitor what will happen on next days.

**Comment by ollo69** [comment]
Just to keep you informed, second day log. Basic same behavior of first day:

```
2022-08-22 04:30:26.351 INFO (MainThread) [custom_components.skyq.classes.power] I0040 - Device is not available. Nightly reboot?: SkyQ Platinum
2022-08-22 04:30:46.856 INFO (MainThread) [custom_components.skyq.classes.power] I0040 - Device is not available. Nightly reboot?: SkyQ Mini Letto
2022-08-22 04:32:20.643 INFO (MainThread) [custom_components.skyq.sensor] I0020 - Device is not available overnight, ECO/reboot?: SkyQ Platinum Used Storage
2022-08-22 04:32:32.758 INFO (MainThread) [custom_components.skyq.classes.power] I0010 - Device is now available: SkyQ Platinum
2022-08-22 04:33:34.001 WARNING (MainThread) [custom_components.skyq.classes.power] W0020 - Device is not available: SkyQ Mini Letto
2022-08-22 04:35:50.985 INFO (MainThread) [custom_components.skyq.classes.power] I0010 - Device is now available: SkyQ Mini Letto
2022-08-22 04:37:17.506 INFO (MainThread) [custom_components.skyq.sensor] I0010 - Device is now available: SkyQ Platinum Used Storage
2022-08-22 04:45:26.953 INFO (MainThread) [custom_components.skyq.classes.power] I0040 - Device is not available. Nightly reboot?: SkyQ Mini Letto
2022-08-22 04:47:10.997 INFO (MainThread) [custom_components.skyq.classes.power] I0010 - Device is now available: SkyQ Mini Letto
```

**Comment by RogerSelwyn** [comment]
Changed to 6 minute timeout for mini

https://github.com/RogerSelwyn/Home_Assistant_SkyQ_MediaPlayer/releases/tag/v2.9.10

**Comment by ollo69** [comment]
Installed 👍

**Comment by ollo69** [comment]
Now is perfect:

```
2022-08-23 04:30:28.030 INFO (MainThread) [custom_components.skyq.classes.power] I0040 - Device is not available. Nightly reboot?: SkyQ Platinum
2022-08-23 04:30:48.038 INFO (MainThread) [custom_components.skyq.classes.power] I0040 - Device is not available. Nightly reboot?: SkyQ Mini Letto
2022-08-23 04:32:32.148 INFO (MainThread) [custom_components.skyq.classes.power] I0010 - Device is now available: SkyQ Platinum
2022-08-23 04:35:52.192 INFO (MainThread) [custom_components.skyq.classes.power] I0010 - Device is now available: SkyQ Mini Letto
2022-08-23 04:45:28.138 INFO (MainThread) [custom_components.skyq.classes.power] I0040 - Device is not available. Nightly reboot?: SkyQ Mini Letto
2022-08-23 04:47:12.437 INFO (MainThread) [custom_components.skyq.classes.power] I0010 - Device is now available: SkyQ Mini Letto
```

Thanks so much, I close this PR.

**Pull request closed without merging**
